# Q2 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.

fibonacciSeq = [1, 2]
evenFibonacciSeq = []
for i in range(1,4000000):
    n = (fibonacciSeq[i-1]+fibonacciSeq[i])
    if n < 4000000:
        fibonacciSeq.append(n)
    else:
        break

for m in fibonacciSeq:
    if m % 2 == 0:
        evenFibonacciSeq.append(m)

sumEvenFibonacciSeq = sum(evenFibonacciSeq)
print(sumEvenFibonacciSeq)